name: ClashX

on: 
  workflow_dispatch:

env:
  FASTLANE_SKIP_UPDATE_CHECK: true

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: import certs
      run: |
        echo `/usr/bin/xcodebuild -version`
    - name: setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: install deps
      run: |
        bash install_dependency.sh
    
    - name: update beta build version
      if: contains(github.event.head_commit.message, '[beta]') && !startsWith(github.ref, 'refs/tags/')
      run: |
        bundle exec fastlane beta
        bundle exec fastlane run set_info_plist_value path:ClashX/Info.plist key:BETA value:YES

    - name: build
      env:
        CODE_SIGN_IDENTITY: "Developer ID Application: Fuzhou West2Online Internet Inc. (MEWHFZ92DY)"
      run: |
        cd ClashX
        python3 add_build_info.py
        cd ..
        bundle exec fastlane build
        echo "Checking SMJobBless Vailded"
        python SMJobBlessUtil.py check ClashX.app
        echo "Check done"

    - name: setup node
      if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[appcenter]')
      uses: actions/setup-node@v3
      with:
        node-version: '10.x'

    - name: create dmg
      if: startsWith(github.ref, 'refs/tags/') || contains(github.event.head_commit.message, '[appcenter]')
      run: |
        npm install --global create-dmg
        create-dmg ClashX.app
        mv ClashX*.dmg ClashX.dmg

   
    - name: upload build to github
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ClashX.dmg
        draft: true
        prerelease: true
